# Generated by Django 5.1.1 on 2024-09-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_keyboard_created_at_keyboard_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
